- name: catalogue
  hosts: catalogue 
  become: yes 
  tasks: 
    - name: Disabling the Current NodeJS and enabling NodeJS:20
      ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:20 -y

    - name: Installing NodeJS:20
      ansible.builtin.package:
        name: nodejs 
        state: present 

    - name: creating roboshop user
      ansible.builtin.user:
        name: roboshop 

    - name: creating /app directory 
      ansible.builtin.file:
        path: /app 
        state: directory

    - name: Downoloading the catalogue.zip 
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
        dest: /tmp 

    - name: unzipping catalogue.zip 
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip 
        remote_src: yes 
        dest: /app 