- name: catalogue
  hosts: catalogue 
  become: yes 
  tasks: 
    - name: Disabling the Current NodeJS and enabling NodeJS:20
      ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:20 -y